ARG RUBY_VERSION
ARG BUNDLER_VERSION

# See explanation below
FROM ruby:$RUBY_VERSION AS assets

# Configure bundler and PATH
ENV LANG=C.UTF-8 \
  GEM_HOME=/bundle \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3
ENV BUNDLE_PATH $GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH \
  BUNDLE_BIN=$BUNDLE_PATH/bin
ENV PATH /app/bin:$BUNDLE_BIN:$PATH

COPY . /app

ENV DEBIAN_FRONTEND noninteractive
ARG NODE_MAJOR
RUN apt-get update && \
    curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y build-essential yarn nodejs && \
    cd /app && \
    gem install bundler:$BUNDLER_VERSION && \
    bundle install && \
    RAILS_ENV=production rails assets:precompile



FROM ruby:$RUBY_VERSION

# Configure bundler and PATH
ENV LANG=C.UTF-8 \
  GEM_HOME=/bundle \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3
ENV BUNDLE_PATH $GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH \
  BUNDLE_BIN=$BUNDLE_PATH/bin
ENV PATH /app/bin:$BUNDLE_BIN:$PATH

# We use an external Aptfile to install extra packages
COPY .dockerprod/Aptfile /tmp/Aptfile

RUN groupadd -g 10000 rails && \
    useradd -g rails -M -u 10000 -s /bin/bash -d /app rails && \
    apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    $(cat /tmp/Aptfile | xargs) && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/*log


# Copy the rails application
COPY --chown=rails:rails . /app

# Copy gems and and assets from previous step.
COPY --from=assets $GEM_HOME $GEM_HOME
COPY --from=assets --chown=rails:rails /app/public /app/public

# Create a directory for the app code
RUN mkdir -p /app && mkdir -p /bundle && chown rails:rails /app && chown rails:rails /bundle

WORKDIR /app

# According to this issue on github:
# https://github.com/moby/moby/issues/12886#issuecomment-480575928
# it's possible to have multiple .dockerignore files for different dockerfiles.
#
# Unfortunately, I could not make it work so I finally decided to not ignore the tests
# files in the .dockerignore file and delete them in the following step.
ARG BUNDLER_VERSION
RUN rm -r  test/* && \
    gem install bundler:$BUNDLER_VERSION && \
    bundle install

USER rails
WORKDIR /app

ENTRYPOINT ["bin/entrypoint.sh"]
